apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: spring-petclinic-rest
  description: the classic petclinic API from swagger.io, pulled from a live endpoint.
spec:
  type: openapi
  lifecycle: production
  owner: tap-gui
  system: tap
  definition:
    $json: https://github.com/sreeramsunkara/spring-petclinic-rest/blob/master/api-docs.json
