apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-petclinic-rest
  namespace: tap-dev
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-petclinic-rest
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  source:
    git:
      url: https://github.com/sreeramsunkara/spring-petclinic-rest.git
      ref:
        branch: master
  env:
  - name: SPRING_PROFILES_ACTIVE
    value: hsqldb,spring-data-jpa

